### ISSUE TITLE
unknown repository after migration

### ISSUE THREAD

**Issue by mattiaerre** [opencomponents/oc-testing#4]
# Description

there was an outstanding PR waiting to be merged that has been ported to this new repo when the `opencomponents` organization was created. Unfortunately, we lost the original branch from which this PR was proposed. I managed to create a new branch w/ these changes so that it will be possible to create a new PR out of it and then address the outstanding comments from the original one.

PR: #1 

new branch: https://github.com/opencomponents/oc-testing/tree/jestify

new PR: #3

**Comment by mattiaerre** [comment]
I would also use Jest only and completely get rid of Mocha; let me know what you think.

// cc @matteofigus @nickbalestra

**Comment by nickbalestra** [comment]
Yes, please, do it!

**Comment by mattiaerre** [comment]
closing because of #3
